apiVersion: v1
kind: Service
metadata:
  labels:
    v1.min.io/tenant: myminio
  name: minio
  namespace: minio
spec:
  clusterIP: 10.41.33.244
  clusterIPs:
    - 10.41.33.244
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: data
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    v1.min.io/tenant: myminio
  sessionAffinity: None
  type: ClusterIP
