apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-env
  namespace: minio
data:
  MINIO_BROWSER: 'on'
  MINIO_PROMETHEUS_AUTH_TYPE: public
  MINIO_PROMETHEUS_JOB_ID: minio
  MINIO_PROMETHEUS_URL: >-
    http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local:9090
