apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
  namespace: minio
data:
  config.env: >
    export MINIO_BROWSER="on"

    export MINIO_PROMETHEUS_AUTH_TYPE="public"

    export
    MINIO_PROMETHEUS_URL="http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local:9090"

    export MINIO_PROMETHEUS_JOB_ID="minio"
